### ISSUE TITLE
1.4.56.1 Failed to start the minecraft server

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/carpet-discarpet#19]
As it says in the title.
The release for 1.4.56.1 crashes my server on start, where 1.4.56 starts without error.
My server is 1.18.1

```
[21:06:33] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'carpet'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.12.11.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.11.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.11.jar:?]
Caused by: java.lang.IllegalArgumentException: interface org.javacord.api.entity.user.User already has a registered OutputConverter
        at carpet.script.annotation.OutputConverter.registerToValue(OutputConverter.java:126) ~[fabric-carpet-1.18-1.4.56+v211130.jar:?]
        at Discarpet.Discarpet.onGameStarted(Discarpet.java:93) ~[discarpet-1.18-1.4.56.1.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at carpet.CarpetServer.onGameStarted(CarpetServer.java:76) ~[fabric-carpet-1.18-1.4.56+v211130.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.11.jar:?]
        ... 15 more
```

**Comment by replaceitem** [comment]
I accidentally built discarpet with a half-done change, that's not yet committed.
Will upload a new jar later.

**Comment by replaceitem** [comment]
Alright, i edited the release. Just download the jar file again, and it should work!
