### ISSUE TITLE
__on_system_message does not fire for commands run from __on_discord_message

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/carpet-discarpet#20]
This is a very specific edge case that one would not normally hit, but I've hit it in my use case. It might be worth looking into in case it is a wider reaching issue.

I've stripped down my code to a minimal repro snippet:
```
global_sys_recursion = 0;
__on_system_message(text, m_type, entity) -> (
	global_sys_recursion += 1;
	if(global_sys_recursion >= 5, return());
	
	print(player('all'), m_type);
	if (m_type~'announcement',
		msg = text~'\\[.+\\] (.+)';
		print(player('all'), msg);
	);
);

__on_discord_message(message) -> (
	user = message~'user';
	if (user == null || user~'is_self', return());
	
	msg = message~'readable_content';
	if (length(msg) == 0, return());
	
	command = msg~'!console (.+)';
	if (command != null,
		run(command);
	);
);
```

This code allows you to run console commands from Discord. The issue arises when you try to run `!console say something`. The command runs fine and `[Server] something` is put in chat, but `__on_system_message` fails to run as nothing is printed.
Whereas typing `say something` directly into the console correctly hits all prints in `__on_system_message`.

This looks like a logger hierarchy issue of sorts, potentially. As I see Javacord reporting the command output in my console when `!console` is used from my Discord server.
```
[06:40:16] [Javacord - Central ExecutorService - 14/INFO]: [Server] This should print no matter what.
[06:43:01] [Server thread/INFO]: <GunnyWaffle> Welp.. that don't work, filing an issue.
```
vs direct use in the console
```
say test
[06:59:39] [Server thread/INFO]: [Server] test
```

Let me know if my snippet fails to repro, I'll provide more context/code as necessary. I can't test this right now without spinning up another bot/server.

PS: v1.0.0 runs well for me so far, thanks!

**Comment by replaceitem** [comment]
This looks like a tough issue, i could trace execution all the way down to evaluating the expression inside the `system_message` event, where somehow, an internal expression exception appears, which is being catched, and throws a new error saying "Your expression result is incorrect: Thread interrupted" ([`Expression.java` line 960](https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/script/Expression.java#L960)). This tells me its an issue with the event being executed in another thread (JavaCord listener thread) but i have no idea what to do about that.

**Comment by replaceitem** [comment]
Discord events now run on the main thread (06e6c0802942456bf44481aa8bc294739ae04a62)
However, from my testing this keeps happening, since carpet itself prevents events from executing inside events.

**Comment by GunnyWaffle** [comment]
Where this once failed silently, it now crashes in v1.3.0
```
[00:15:08] [Server thread/ERROR]: Unexpected exception while running Scarpet code
java.lang.NullPointerException: Unregistered output type: class org.javacord.core.entity.user.UserImpl. Register in OutputConverter
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at carpet.script.annotation.OutputConverter.get(OutputConverter.java:79) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at Discarpet.script.values.common.DiscordValue.of(DiscordValue.java:29) ~[discarpet-1.3.0.jar:?]
        at Discarpet.script.values.common.DiscordValue.of(DiscordValue.java:35) ~[discarpet-1.3.0.jar:?]
        at Discarpet.script.values.MessageValue.getProperty(MessageValue.java:23) ~[discarpet-1.3.0.jar:?]
        at Discarpet.script.values.common.DiscordValue.in(DiscordValue.java:40) ~[discarpet-1.3.0.jar:?]
        at carpet.script.Expression$8.eval(Expression.java:401) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Fluff$AbstractOperator.lambda$lazyEval$0(Fluff.java:244) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression.lambda$extractOp$17(Expression.java:1345) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.LazyValue.evalValue(LazyValue.java:21) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.language.Operators.lambda$apply$49(Operators.java:300) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression$5.lazyEval(Expression.java:326) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression.lambda$extractOp$17(Expression.java:1345) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.language.ControlFlow.lambda$apply$5(ControlFlow.java:33) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression$16.lazyEval(Expression.java:576) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression.lambda$extractOp$20(Expression.java:1353) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.value.FunctionValue.execute(FunctionValue.java:254) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetScriptHost.lambda$callUDF$30(CarpetScriptHost.java:834) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression.evalValue(Expression.java:947) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetScriptHost.callUDF(CarpetScriptHost.java:833) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetEventServer.runEventCall(CarpetEventServer.java:1221) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetEventServer$Callback.execute(CarpetEventServer.java:111) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetEventServer$CallbackList.lambda$call$0(CarpetEventServer.java:249) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.utils.GlocalFlag.runIfEnabled(GlocalFlag.java:60) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetEventServer$CallbackList.call(CarpetEventServer.java:224) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at Discarpet.script.events.DiscordEvents.callHandlerInBotApps(DiscordEvents.java:107) ~[discarpet-1.3.0.jar:?]
        at Discarpet.script.events.DiscordEvents$1.onDiscordMessage(DiscordEvents.java:50) ~[discarpet-1.3.0.jar:?]
        at Discarpet.script.events.DiscarpetEventsListener.lambda$onMessageCreate$0(DiscarpetEventsListener.java:36) ~[discarpet-1.3.0.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zbp000$modifiedRunLoop(MinecraftServer.java:2905) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[00:15:08] [Server thread/INFO]: Callback failed: __on_discord_message(message) -> (
   user = message HERE>> ~'user';
   // stop talking to yourself
Error while evaluating expression: java.lang.NullPointerException: Unregistered output type: class org.javacord.core.entity.user.UserImpl. Register in OutputConverter in discord at line 135, pos 18
```
