### ISSUE TITLE
Message property 'user' crashes scarpet in v1.3.0

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/carpet-discarpet#29]
I updated to v1.3.0 and found that I am unable to query 'user' on message values.
```
[00:22:18] [Server thread/ERROR]: Unexpected exception while running Scarpet code
java.lang.NullPointerException: Unregistered output type: class org.javacord.core.entity.user.UserImpl. Register in OutputConverter
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at carpet.script.annotation.OutputConverter.get(OutputConverter.java:79) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at Discarpet.script.values.common.DiscordValue.of(DiscordValue.java:29) ~[discarpet-1.3.0.jar:?]
        at Discarpet.script.values.common.DiscordValue.of(DiscordValue.java:35) ~[discarpet-1.3.0.jar:?]
        at Discarpet.script.values.MessageValue.getProperty(MessageValue.java:23) ~[discarpet-1.3.0.jar:?]
        at Discarpet.script.values.common.DiscordValue.in(DiscordValue.java:40) ~[discarpet-1.3.0.jar:?]
        at carpet.script.Expression$8.eval(Expression.java:401) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Fluff$AbstractOperator.lambda$lazyEval$0(Fluff.java:244) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression.lambda$extractOp$17(Expression.java:1345) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.LazyValue.evalValue(LazyValue.java:21) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.language.Operators.lambda$apply$49(Operators.java:300) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression$5.lazyEval(Expression.java:326) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression.lambda$extractOp$17(Expression.java:1345) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.language.ControlFlow.lambda$apply$5(ControlFlow.java:33) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression$16.lazyEval(Expression.java:576) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression.lambda$extractOp$20(Expression.java:1353) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.value.FunctionValue.execute(FunctionValue.java:254) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetScriptHost.lambda$callUDF$30(CarpetScriptHost.java:834) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.Expression.evalValue(Expression.java:947) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetScriptHost.callUDF(CarpetScriptHost.java:833) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetEventServer.runEventCall(CarpetEventServer.java:1221) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetEventServer$Callback.execute(CarpetEventServer.java:111) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetEventServer$CallbackList.lambda$call$0(CarpetEventServer.java:249) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.utils.GlocalFlag.runIfEnabled(GlocalFlag.java:60) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at carpet.script.CarpetEventServer$CallbackList.call(CarpetEventServer.java:224) ~[fabric-carpet-1.18.2-1.4.69+v220331.jar:?]
        at Discarpet.script.events.DiscordEvents.callHandlerInBotApps(DiscordEvents.java:107) ~[discarpet-1.3.0.jar:?]
        at Discarpet.script.events.DiscordEvents$1.onDiscordMessage(DiscordEvents.java:50) ~[discarpet-1.3.0.jar:?]
        at Discarpet.script.events.DiscarpetEventsListener.lambda$onMessageCreate$0(DiscarpetEventsListener.java:36) ~[discarpet-1.3.0.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zbp000$modifiedRunLoop(MinecraftServer.java:2905) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[00:22:18] [Server thread/INFO]: Callback failed:    // return(); // PENDING ISSUE https://github.com/replaceitem/carpet-discarpet/issues/20
   user = message HERE>> ~'user';
   // stop talking to yourself
Error while evaluating expression: java.lang.NullPointerException: Unregistered output type: class org.javacord.core.entity.user.UserImpl. Register in OutputConverter in discord at line 136, pos 18
```
The code that fails:
```
__on_discord_message(message) -> (
	user = message~'user';
);
```

**Comment by replaceitem** [comment]
Thats a lot of bugs...
