### ISSUE TITLE
Server crash __on_system_message in Carpet 1.4.84

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/carpet-discarpet#38]
When updating to Carpet 1.4.84, any use of `__on_system_message` causes the server to crash.
This problem is not present in Carpet 1.4.83.
```
[06:52:05] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void carpet.script.CarpetEventServer$CallbackList.call(java.util.function.Supplier, java.util.function.Supplier)'
        at Discarpet.script.events.MiscEvents$1.onSystemMessage(MiscEvents.java:40) ~[discarpet-1.19.1-1.4.6.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zib000$onSystemMessage(MinecraftServer.java:3764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_43496(MinecraftServer.java:996) ~[server-intermediary.jar:?]
        at net.minecraft.class_2168.method_9226(class_2168.java:302) ~[server-intermediary.jar:?]
        at carpet.utils.Messenger.m(Messenger.java:236) ~[fabric-carpet-1.19.2-1.4.84+v221018.jar:?]
        at carpet.script.CarpetScriptServer.addScriptHost(CarpetScriptServer.java:302) ~[fabric-carpet-1.19.2-1.4.84+v221018.jar:?]
        at carpet.script.CarpetScriptServer.initializeForWorld(CarpetScriptServer.java:137) ~[fabric-carpet-1.19.2-1.4.84+v221018.jar:?]
        at carpet.CarpetServer.onServerLoadedWorlds(CarpetServer.java:109) ~[fabric-carpet-1.19.2-1.4.84+v221018.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zbd000$serverLoadedWorlds(MinecraftServer.java:2292) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by replaceitem** [comment]
Fixed by rebuilding with new carpet version in eae9d52cf17cc8b3fad828057cd2fb7276f17605
