### ISSUE TITLE
Minecraft 1.19.3 Websocket closed before READY packet was received

### ISSUE THREAD

**Issue by Player505** [replaceitem/carpet-discarpet#39]
I was running discarpet on my Minecraft 1.19.3 server for a while before updating a few mods and it was going fine. Since updating it has now returned this error

```
Jan 16 00:51:54 minecraft conmon[11179]: [00:51:54] [Server thread/WARN]: Could not login bot Minceraft
Jan 16 00:51:54 minecraft conmon[11179]: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
Jan 16 00:51:54 minecraft conmon[11179]:         at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at Discarpet.config.Bot.<init>(Bot.java:35) ~[discarpet-1.19.2-1.4.7.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at Discarpet.Discarpet.loadBots(Discarpet.java:138) ~[discarpet-1.19.2-1.4.7.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at Discarpet.Discarpet.loadConfig(Discarpet.java:118) ~[discarpet-1.19.2-1.4.7.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at Discarpet.commands.DiscarpetCommand.lambda$register$7(DiscarpetCommand.java:64) ~[discarpet-1.19.2-1.4.7.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.class_2170.method_9249(class_2170.java:279) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.class_2170.method_44252(class_2170.java:272) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.class_3176.method_20799(class_3176.java:526) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.class_1255.method_5386(class_1255.java:67) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.server.MinecraftServer.handler$zce000$modifiedRunLoop(MinecraftServer.java:3917) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at java.lang.Thread.run(Unknown Source) ~[?:?]
Jan 16 00:51:54 minecraft conmon[11179]: Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
Jan 16 00:51:54 minecraft conmon[11179]:         at org.javacord.core.DiscordApiImpl.lambda$new$6(DiscordApiImpl.java:664) ~[org_javacord_javacord-core-3.5.0-181484acc4cd0a16.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:515) ~[org_javacord_javacord-core-3.5.0-181484acc4cd0a16.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[com_neovisionaries_nv-websocket-client-2.14-4fd9dbe62fc77c4e.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3758) ~[com_neovisionaries_nv-websocket-client-2.14-4fd9dbe62fc77c4e.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3724) ~[com_neovisionaries_nv-websocket-client-2.14-4fd9dbe62fc77c4e.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3713) ~[com_neovisionaries_nv-websocket-client-2.14-4fd9dbe62fc77c4e.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539) ~[com_neovisionaries_nv-websocket-client-2.14-4fd9dbe62fc77c4e.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78) ~[com_neovisionaries_nv-websocket-client-2.14-4fd9dbe62fc77c4e.jar:?]
Jan 16 00:51:54 minecraft conmon[11179]:         at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[com_neovisionaries_nv-websocket-client-2.14-4fd9dbe62fc77c4e.jar:?]
```

I haven't had a opportunity to isolate the issue yet to see if it's a conflict with another mod.

**Comment by replaceitem** [comment]
Have you checked your config still has the right and valid token?

**Comment by Player505** [comment]
I think so? I've also reset it twice and copied the new token to the config but still same issue

**Comment by Player505** [comment]
Fixed the issue. Removed the config file and regenerated a new one. Must've messed up somewhere
