### ISSUE TITLE
1.21.3 Javacord unhandled exception upon Discord message

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/carpet-discarpet#53]
I'm currently testing 1.21.3 for production deployment and have come across an exception each time a Discord message is sent.
This exception occurs any time:
- A user sends a message in the Discord channel.
- The bot sends a message in the Discord channel.
- A webhook message is sent in the Discord channel.

```
[19:23:10] [Javacord - Central ExecutorService - 1/ERROR]: Unhandled exception in a listener thread for <server name here>!
java.lang.NoSuchMethodError: 'void net.minecraft.server.MinecraftServer.method_18858(java.lang.Runnable)'
        at knot/net.replaceitem.discarpet.script.events.DiscarpetEventsListener.callEventOnGameThread(DiscarpetEventsListener.java:108) ~[discarpet-1.20.5-1.5.5.jar:?]
        at knot/net.replaceitem.discarpet.script.events.DiscarpetEventsListener.onMessageCreate(DiscarpetEventsListener.java:45) ~[discarpet-1.20.5-1.5.5.jar:?]
        at knot/org.javacord.core.util.event.EventDispatcher.lambda$dispatchMessageCreateEvent$272(EventDispatcher.java:9168) ~[org_javacord_javacord-core-3.8.0-732e24faa0947882.jar:?]
        at knot/org.javacord.core.util.event.EventDispatcherBase.lambda$dispatchEvent$12(EventDispatcherBase.java:215) ~[org_javacord_javacord-core-3.8.0-732e24faa0947882.jar:?]
        at knot/org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$20(EventDispatcherBase.java:289) ~[org_javacord_javacord-core-3.8.0-732e24faa0947882.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

Let me know if you would like or need further information.
As always, thank you for maintaining and updating this wonderful mod!

**Comment by replaceitem** [comment]
Just needed a rebuild because intermediary mappings changed. I just checked for 1.21.3 whether discarpet still works, and it did, so i just bumped the tagged version on modrinth. Turns out the old jars don't.
https://modrinth.com/mod/discarpet/version/OJii3RPI
